### ISSUE TITLE
[api redesign] get rid of the 'produced message' class

### ISSUE THREAD

**Issue by eggsby** [cjdev/kafka-rx#8]
In a continued effort to reduce the public api surface we should get rid of the `ProducedMessage` class.

Now that we have an independent commit context it makes sense to use this instead of the `ProducedMessage` class (which only exists so that we can tie a commit method from a source message to a target message)

Instead `.produce` could return a: `Committable[ProducerRecord[K, V]]`

We would need a way to thread this commit context through the kafka callback the way we pass around the underlying commitFn now.

Similarly, we could have a `.saveToKafka` implicit on `Committable[ProducerRecord[K, V]]`

**Comment by mkflagstad** [comment]
While we are at it we could probably get rid of `Message[K,V]` as well:

https://github.com/cjdev/kafka-rx/blob/master/src/main/scala/com/cj/kafka/rx/package.scala#L65

**Comment by eggsby** [comment]
implemented @ 22363d098ca762cc52685a96cccfddc366e48aa4
